# Generated by Django 5.0.3 on 2024-04-08 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_rename_state_id_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
